// Geovisor - OpenLayers | Variables Globales
export const variables = {

    title: 'Geoportal DANE -Geovisor Realidad Aumentada CNPV 2018 ', //Cambielo por el título de su geovisor
    description: 'Geoportal DANE - Geovisor Realidad Aumentada CNPV 2018',
    country: 'Colombia',
    place: ' Todos los departamentos ',
    fuente: "Censo Nacional de Población y Vivienda 2018",
    fuenteURL: "https://www.dane.gov.co/index.php/estadisticas-por-tema/demografia-y-poblacion/censo-nacional-de-poblacion-y-vivenda-2018",
    year: ' 2023 ',
    map: null,
    urlTemas: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/visores/temas.php',
    urlVariables: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/visores/variables8.php',//enlace/servicio  que trae los datos de la variable seleccionada
    urlVariablesProductos: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/sipsa/productos.php',//enlace/servicio  que trae los datos de la variable seleccionada
    //codVisor: "68", //Ponga el codigo que corresponde a SU VISOR
    //varVariable: "01440001", //Ponga el codigo de la CATEGORIA que corresponda a su visor
    codVisor: "67",
    varVariable: "43501001",
    series: [0, 0, 0, 0, 0],
    urlUE: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/censo_economico/unidades2_segment.php?min=y&codigo_municipio=",
    urlCount: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/censo_economico/unidades2_segment.php?count=y&codigo_municipio=",
    urlCentroids: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/licencias-construccion/centroides_elic.php?depto=",
    urlDivipolaV2: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/equipamientos/table-list-extent.php",
    urlCentroidsGeneral: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/licencias-construccion/centroides.php?",
    urlPlacesGoogle: "https://maps.googleapis.com/maps/api/place/findplacefromtext/json",
    urlMarkers: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/poblacion/centroides_manzanas.php?coordx=-75.5818&coordy=6.2248&longitud=4000",
    key: "pk.eyJ1IjoiYXBwbW92aWxkYW5lIiwiYSI6ImNrbzY4b2tiajFxN2cyb3F3YnR1NDF6eWkifQ.mVlSJXQZVl4CNmQpZ1pXNA",
    key: "",
    baseMaps: {
        'Gris': 'https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        'Noche': 'https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
        'OSM': 'https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',
        'Satelital': 'https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',
    },
    baseMapCheck: "Noche",  // Ponga el MAPA BASE que quiere por defecto
    layers: {
        // manzanas: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "manzanas",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_mzn1/MGN_2018_URB_MANZANA/cod_dane-viv/{z}/{x}/{y}",
        //     title: 'Manzanas',
        //     visible: true,
        //     checked: true,
        //     hideToc: false,
        //     minZoom: 11,
        //     maxZoom: 21,
        //     style: {
        //         // 'fill-extrusion-color': [
        //         //     "step",
        //         //     ["to-number", ["get", "viv"]],
        //         //     "#fff5f0",
        //         //     25,
        //         //     "#fdbea5",
        //         //     79,
        //         //     "#fc7050",
        //         //     250,
        //         //     "#d42020",
        //         //     667,
        //         //     "#67000d"
        //         // ],
        //         // 'fill-extrusion-height': ["*", 1, ["get", "viv"]],
        //     },
        //     ol: null,
        //     layer: "MGN_2018_URB_MANZANA",
        //     typeLayer: "fill-extrusion",
        //     clickable: true
        // },
        // manzanasVariacion: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "manzanasVariacion",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_mzn1/MGN_2018_URB_MANZANA/cod_dane-variacion/{z}/{x}/{y}",
        //     title: 'Variación manzanas MGN 2021',
        //     visible: false,
        //     checked: false,
        //     hideToc: true,
        //     minZoom: 4,
        //     maxZoom: 21,
        //     style: {
        //         'fill-extrusion-color': [
        //             "step",
        //             ["to-number", ["get", "variacion"]],
        //             "#fff5f0",
        //             25,
        //             "#fdbea5",
        //             79,
        //             "#fc7050",
        //             250,
        //             "#d42020",
        //             667,
        //             "#67000d"
        //         ],
        //         'fill-extrusion-height': ["*", 1, ["get", "variacion"]],
        //     },
        //     ol: null,
        //     layer: "MGN_2018_URB_MANZANA",
        //     typeLayer: "fill-extrusion",
        //     clickable: true
        // },
        manzanas2022: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "manzanas2022",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_mzn/MGN_2018_URB_MANZANA/cod_dane-viviendas/{z}/{x}/{y}",
            title: 'Manzanas 2022',
            visible: true,
            hideToc: false,
            checked: true,
            minZoom: 8,
            maxZoom: 21,
            style: {
                // 'fill-extrusion-color': [
                //     "step",
                //     ["to-number", ["get", "viviendas"]],
                //     "#fff5f0",
                //     25,
                //     "#fdbea5",
                //     79,
                //     "#fc7050",
                //     250,
                //     "#d42020",
                //     667,
                //     "#67000d"
                // ],
                // 'fill-extrusion-height': ["*", 1, ["get", "viviendas"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        // manzanasVariacion2022: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "manzanasVariacion2022",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_mzn/MGN_2018_URB_MANZANA/cod_dane-variacion/{z}/{x}/{y}",
        //     title: 'Variación manzanas MGN 2022',
        //     visible: false,
        //     checked: false,
        //     hideToc: true,
        //     minZoom: 4,
        //     maxZoom: 21,
        //     style: {
        //         'fill-extrusion-color': [
        //             "step",
        //             ["to-number", ["get", "variacion"]],
        //             "#fff5f0",
        //             25,
        //             "#fdbea5",
        //             79,
        //             "#fc7050",
        //             250,
        //             "#d42020",
        //             667,
        //             "#67000d"
        //         ],
        //         'fill-extrusion-height': ["*", 1, ["get", "variacion"]],
        //     },
        //     ol: null,
        //     layer: "MGN_2018_URB_MANZANA",
        //     typeLayer: "fill-extrusion",
        //     clickable: true
        // },
        // seccionesRurales: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "secciones",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_rursecc1/MGN_2018_URB_MANZANA/secr_ccnct-secr_viv/{z}/{x}/{y}",
        //     title: 'Secciones rurales',
        //     visible: false,
        //     checked: false,
        //     hideToc: true,
        //     minZoom: 4,
        //     maxZoom: 21,
        //     style: {
        //         'fill-extrusion-color': [
        //             "step",
        //             ["to-number", ["get", "secr_viv"]],
        //             "#fff5f0",
        //             25,
        //             "#fdbea5",
        //             79,
        //             "#fc7050",
        //             250,
        //             "#d42020",
        //             667,
        //             "#67000d"
        //         ],
        //         'fill-extrusion-height': ["*", 1, ["get", "secr_viv"]],
        //     },
        //     ol: null,
        //     layer: "MGN_2018_URB_MANZANA",
        //     typeLayer: "fill-extrusion",
        //     clickable: true
        // },
        // seccionesRurales2022: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "secciones2022",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_rursecc/MGN_2018_URB_MANZANA/secr_ccnct-secr_viv/{z}/{x}/{y}",
        //     title: 'Secciones 2022',
        //     visible: false,
        //     checked: false,
        //     hideToc: true,
        //     minZoom: 4,
        //     maxZoom: 21,
        //     style: {
        //         'fill-extrusion-color': [
        //             "step",
        //             ["to-number", ["get", "secr_viv"]],
        //             "#fff5f0",
        //             25,
        //             "#fdbea5",
        //             79,
        //             "#fc7050",
        //             250,
        //             "#d42020",
        //             667,
        //             "#67000d"
        //         ],
        //         'fill-extrusion-height': ["*", 1, ["get", "secr_viv"]],
        //     },
        //     ol: null,
        //     layer: "MGN_2018_URB_MANZANA",
        //     typeLayer: "fill-extrusion",
        //     clickable: true
        // },
        
        municipios: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "mpios_vt",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_mpio/mgn_2020_mpio_politico/mpio_ccnct/{z}/{x}/{y}",
            title: 'Municipios',
            visible: true,
            checked: true,
            minZoom: 7,
            maxZoom: 10,
            style: {
                // "line-color": '#ffffff',
                // "line-width": 1
            },
            ol: null,
            layer: "mgn_2020_mpio_politico",
            typeLayer: "fill-extrusion",
            clickable: true,
            hideToc: true
        },
        departamentos: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "deptos_vt",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_dpto/mgn_2020_dpto_politico/dpto_ccdgo/{z}/{x}/{y}",
            title: 'Departamentos',
            visible: true,
            checked: true,
            minZoom: 3,
            maxZoom: 7,
            style: {
                // "line-color": '#7F3872',
                // "line-width": 1
            },
            ol: null,
            layer: "mgn_2020_dpto_politico",
            typeLayer: "fill-extrusion",
            clickable: true,
            hideToc: true
        },
        // municipiosSel: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "mpios_vt2",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_mpio/mgn_2020_mpio_politico/mpio_ccnct/{z}/{x}/{y}",
        //     title: 'Municipios sel',
        //     visible: true,
        //     checked: false,
        //     hideToc: true,
        //     minZoom: 7,
        //     maxZoom: 21,
        //     style: {
        //         "line-color": '#95172A',
        //         "line-width": 1,
        //         "line-opacity": 1
        //     },
        //     ol: null,
        //     layer: "mgn_2020_mpio_politico",
        //     typeLayer: "line",
        //     clickable: false
        // },
        // departamentoSel: {
        //     tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
        //     id: "deptos_vt2",
        //     url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_dpto/mgn_2020_dpto_politico/dpto_ccdgo/{z}/{x}/{y}",
        //     title: 'Departamentos sel',
        //     visible: true,
        //     checked: false,
        //     minZoom: 1,
        //     maxZoom: 12,
        //     hideToc: true,
        //     style: {
        //         "line-color": '#DC7AFA',
        //         "line-width": 2,
        //         "line-opacity": 1
        //     },
        //     ol: null,
        //     layer: "mgn_2020_dpto_politico",
        //     typeLayer: "line",
        //     clickable: false
        // },
        
    },
    layersInMap: [],
    consulta: "as",
    tematica: JSON.parse(localStorage.getItem('tematica')) != null ? JSON.parse(localStorage.getItem('tematica')) : {
        "GRUPOS": {},
        "SUBGRUPOS": {},
        "TEMAS": [],
        "CATEGORIAS": {}
    },
    tema: null,
    dataArrayDatosMpio: {},
    dataArrayDatos: {},
    dataArrayDatosManzana: {},
    dataRangos: JSON.parse(localStorage.getItem('rangos')) != null ? JSON.parse(localStorage.getItem('rangos')) : {},
    dataRangos: {},
    dataChart: {},
    changeTheme: null,
    coloresLeyend: JSON.parse(localStorage.getItem('leyenda')) != null ? JSON.parse(localStorage.getItem('leyenda')) : {},
    coloresLeyend: {},
    changeLegend: null,
    changeChart: null,
    changeMap: null,
    queryText: {},
    alias: null,
    valorTotal: null,
    pintarCluster: null,
    capas: {},
    legenTheme: null,
    legendChange: null,
    tipoVar: null,
    thematicTheme: null,
    tansparency: 8,
    listaVariables: [],
    labelsData: [],
    dataPie: [],
    changeLoader: null,
    changeData: null,
    updateData: null,
    filterGeo: null,
    deptoSelected: null,
    deptoSelectedFilter: null,
    deptoVariable: null,
    currentZoom: null,
    changeBarChartData: null,
    changePieChartData: null,
    changeDonuChartData: null,
    changeGaugeChartData: null,
    visualGroup: null,
    visualThematic: null,
    state: {
        labels: [],

        datasets: [
            {
                label: '',
                // labels: myLabels,
                backgroundColor: [],
                data: []
            }
        ]
    },
    structureUE: {
        "M": "Manzana",
        "E": "Edificación",
        "UE": "Unidad económica",
        "U": "Unidad",
        "EO": "Cantidad de unidades ocupadas",
        "ED": "Cantidad de unidades desocupadas",
        "EB": "Cantidad de unidades en obra",
        "EF": "Cantidad de unidades fijas",
        "ES": "Cantidad de unidades semifijas",
        "PM": "Cantidad de puestos móviles",
        "VA": "Cantidad de viviendas con actividad económica",
        "OBE": "Cantidad de obras en edificación",
        "SC": "Cantidad de unidades - comercio",
        "SI": "Cantidad de unidades - industria",
        "SS": "Cantidad de unidades - servicios",
        "ST": "Cantidad de unidades - transporte",
        "SCN": "Cantidad de unidades - construcción",
        "SN": "Cantidad de unidades - Sector no aplica",
        "LT": "Latitud",
        "LG": "Longitud",
    },
    unidadesCluster: null,
    distanceCluster: 0,
    loadUE: null,
    changeBaseMap: null,
    activeChart: null,
    baseMapPrev: "Gris",
    changeDepto: null,
    variableAnterior: null,
    municipioSeleccionado: null,
    apiGoogle: 'AIzaSyAOha4Su8EqOFQfDE8NjrS_KdSHfu50WkA',
    changeStyleDepto: null,
    changeStyleMpio: null,
    loadMzCentroids: null,
    unidadesMz: null,
    periodoSeleccionado: { value: '2021-12', label: '2021-12' },
    updatePeriodo: null,
    updatePeriodoHeader: null,
    loadDeptoCentroids: null,
    loadMpioCentroids: null,
    unidadesDepto: null,
    unidadesMpio: null,
    changeVisualization: null,
    updateCharTheme: null,
    updateLegendProportional: null,
    max: null,
    hideProportionalSymbols: null,
    updatePeriodoResult: null,
    periodos: null,
    listaProductos: null,
    productoSeleccionado: null,
    updateListaProductos: null,
    updateProductoSeleccionado: null,
    variablesCampos: {
        '%': 'VARIACION_PP',
        '$': 'PRECIO_PROMEDIO_ACTUAL'
    },
    updateSymbols: null,
    updateToProp: null,
    hideVisualizationSwitch: null,
    coloresDivergentes: {
        "0": "#ca0020",
        "1": "#f4a582",
        "2": "#f7f7f7",
        "3": "#92c5de",
        "4": "#0571b0"
    },
    updatePeriodoTabla: null,
    closer: null,
    updateToProps: null,
    updateProductoResult: null,
    updateProductotabla: null,
    transparencyGeneral: 10,
    versionMGN: "MGN 2022",
    updateActives: null,
    updateLayers: null,
    updateMGNHeader: null,
    ///herramientas de google//////
    marker: null,
    router: {
        line: null,
        start: null,
        finsih: null
    },
    deptoCentro: null,
    markersLayer: null,
    variablesCNPV: {
        "43601001": "V1",
        "43601002": "V2",
        "43601003": "V3",
        "43601004": "V4",
        "43602001": "V5",
        "43602002": "V6",
        "43602002": "V6",
        "43602003": "V7",
        "43602004": "V8",
        "43602005": "V9",
        "43602005": "V9",
        "43603001": "V10",
        "43603002": "V11",
        "43603003": "V12",
        "43603004": "V13",
        "43603005": "V14",
        "43603006": "V15",
        "43603007": "V16",
        "43603008": "V17",
        "43603009": "V18",
        "43603011": "V20",
        "43501004": "V21",
        "43701001": "V22",
        "43701002": "V23",
        "43701003": "V24",
        "43701004": "V25",
        "43701005": "V26",
        "43701006": "V27",
        "43702001": "V28",
        "43702002": "V29",
        "43702003": "V30",
        "43702004": "V31",
        "43501003": "V32",
        "43704001": "V33",
        "43704002": "V34",
        "43703001": "V35",
        "43703002": "V36",
        "43703003": "V37",
        "43703004": "V38",
        "43703005": "V39",
        "43703006": "V40",
        "43703007": "V41",
        "43704003": "V42",
        "43704004": "V43",
        "43704005": "V44",
        "43704006": "V45",
        "43704007": "V46",
        "43704008": "V47",
        "43704009": "V49",
        "43704010": "V50",
        "43704011": "V51",
        "43704012": "V52",
        "43501001": "V54",
        "43501002": "V55",
        "43501005": "V56",
        "43801001": "V57",
        "43801002": "V58",
        "43802001": "V59",
        "43802002": "V60",
        "43802003": "V61",
        "43802004": "V62",
        "43802005": "V63",
        "43802006": "V64",
        "43802007": "V65",
        "43802008": "V66",
        "43802009": "V67",
        "43803005": "V68",
        "43803006": "V69",
        "43803001": "V70",
        "43803002": "V71",
        "43803003": "V72",
        "43803004": "V73"
    },
    markersArray: null,
    actualizarTematica: null,
    marcador: 0,
    menuTematico: null,
    prenderLegend: null,
    apagarLegend: null,
    tipoVariable: null,
    cargaInicial: false,
    changeLegend2: null,
}
export const urlDeploy = 'http://localhost:3000/'