// Geovisor - OpenLayers | Variables Globales
export const variables = {

    title: 'Geoportal DANE - Geovisor variables temáticas MGN ', //Cambielo por el título de su geovisor
    description: 'Geoportal DANE - Geovisor variables temáticas MGN',
    country: 'Colombia',
    place: ' Todos los departamentos ',
    fuente: "Variables temáticas MGN",
    year: ' 2021 ',
    map: null,
    urlTemas: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/visores/temas.php',
    urlVariables: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/visores/variables8.php',//enlace/servicio  que trae los datos de la variable seleccionada
    urlVariablesProductos: 'https://geoportal.dane.gov.co/laboratorio/serviciosjson/sipsa/productos.php',//enlace/servicio  que trae los datos de la variable seleccionada
    codVisor: "56", //Ponga el codigo que corresponde a SU VISOR
    varVariable: "39501001", //Ponga el codigo de la CATEGORIA que corresponda a su visor
    series: [0, 0, 0, 0, 0],
    urlUE: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/censo_economico/unidades2_segment.php?min=y&codigo_municipio=",
    urlCount: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/censo_economico/unidades2_segment.php?count=y&codigo_municipio=",
    urlCentroids: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/licencias-construccion/centroides_elic.php?depto=",
    urlDivipolaV2: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/equipamientos/table-list-extent.php",
    urlCentroidsGeneral: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/licencias-construccion/centroides.php?",
    key: "pk.eyJ1IjoiYXBwbW92aWxkYW5lIiwiYSI6ImNrbzY4b2tiajFxN2cyb3F3YnR1NDF6eWkifQ.mVlSJXQZVl4CNmQpZ1pXNA",
    key: "",
    baseMaps: {
        'Gris': 'https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
        'Noche': 'https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png',
        'OSM': 'https://mt1.google.com/vt/lyrs=r&x={x}&y={y}&z={z}',
        'Satelital': 'https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',
    },
    baseMapCheck: "Noche",  // Ponga el MAPA BASE que quiere por defecto
    layers: {
        manzanas: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "manzanas",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_mzn1/MGN_2018_URB_MANZANA/cod_dane-viv/{z}/{x}/{y}",
            title: 'Manzanas',
            visible: false,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "viv"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "viv"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        manzanasVariacion: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "manzanasVariacion",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_mzn1/MGN_2018_URB_MANZANA/cod_dane-variacion/{z}/{x}/{y}",
            title: 'Variación manzanas MGN 2021',
            visible: false,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "variacion"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "variacion"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        manzanas2022: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "manzanas2022",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_mzn/MGN_2018_URB_MANZANA/cod_dane-viviendas/{z}/{x}/{y}",
            title: 'Manzanas 2022',
            visible: true,
            hideToc: false,
            checked: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "viviendas"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "viviendas"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        manzanasVariacion2022: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "manzanasVariacion2022",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_mzn/MGN_2018_URB_MANZANA/cod_dane-variacion/{z}/{x}/{y}",
            title: 'Variación manzanas MGN 2022',
            visible: false,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "variacion"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "variacion"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        seccionesRurales: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "secciones",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2021_rursecc1/MGN_2018_URB_MANZANA/secr_ccnct-secr_viv/{z}/{x}/{y}",
            title: 'Secciones rurales',
            visible: false,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "secr_viv"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "secr_viv"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        seccionesRurales2022: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "secciones2022",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile3.php?params=capas_geovisores/mgn2022_rursecc/MGN_2018_URB_MANZANA/secr_ccnct-secr_viv/{z}/{x}/{y}",
            title: 'Secciones 2022',
            visible: false,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                'fill-extrusion-color': [
                    "step",
                    ["to-number", ["get", "secr_viv"]],
                    "#fff5f0",
                    25,
                    "#fdbea5",
                    79,
                    "#fc7050",
                    250,
                    "#d42020",
                    667,
                    "#67000d"
                ],
                'fill-extrusion-height': ["*", 1, ["get", "secr_viv"]],
            },
            ol: null,
            layer: "MGN_2018_URB_MANZANA",
            typeLayer: "fill-extrusion",
            clickable: true
        },
        municipiosSel: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "mpios_vt2",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_mpio/mgn_2020_mpio_politico/mpio_ccnct/{z}/{x}/{y}",
            title: 'Municipios sel',
            visible: true,
            checked: false,
            hideToc: true,
            minZoom: 4,
            maxZoom: 21,
            style: {
                "line-color": '#ffffff',
                "line-width": 0,
                "line-opacity": 0
            },
            ol: null,
            layer: "mgn_2020_mpio_politico",
            typeLayer: "line",
            clickable: false
        },
        municipios: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "mpios_vt",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_mpio/mgn_2020_mpio_politico/mpio_ccnct/{z}/{x}/{y}",
            title: 'Municipios',
            visible: true,
            checked: true,
            minZoom: 8,
            maxZoom: 21,
            style: {
                "line-color": '#ffffff',
                "line-width": 1
            },
            ol: null,
            layer: "mgn_2020_mpio_politico",
            typeLayer: "line",
            clickable: false,
            hideToc: true
        },
        departamentos: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "deptos_vt",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_dpto/mgn_2020_dpto_politico/dpto_ccdgo/{z}/{x}/{y}",
            title: 'Departamentos',
            visible: true,
            checked: true,
            minZoom: 3,
            maxZoom: 21,
            style: {
                "line-color": '#7F3872',
                "line-width": 1
            },
            ol: null,
            layer: "mgn_2020_dpto_politico",
            typeLayer: "line",
            clickable: false,
            hideToc: true
        },
        departamentoSel: {
            tipo: "vt",  // Tipos vt: Vector Tile, wms, wfs
            id: "deptos_vt2",
            url: "https://geoportal.dane.gov.co/laboratorio/serviciosjson/vector-tiles/vectortile.php?params=capas_geovisores/mgn2020_dpto/mgn_2020_dpto_politico/dpto_ccdgo/{z}/{x}/{y}",
            title: 'Departamentos sel',
            visible: true,
            checked: false,
            minZoom: 1,
            maxZoom: 12,
            hideToc: true,
            style: {
                "line-color": '#ffffff',
                "line-width": 0,
                "line-opacity": 0
            },
            ol: null,
            layer: "mgn_2020_dpto_politico",
            typeLayer: "line",
            clickable: false
        },
    },
    layersInMap: [],
    consulta: "as",
    tematica: JSON.parse(localStorage.getItem('tematica')) != null ? JSON.parse(localStorage.getItem('tematica')) : {
        "GRUPOS": {},
        "SUBGRUPOS": {},
        "TEMAS": [],
        "CATEGORIAS": {}
    },
    tema: null,
    dataArrayDatosMpio: {},
    dataArrayDatos: {},
    dataArrayDatosManzana: {},
    dataRangos: JSON.parse(localStorage.getItem('rangos')) != null ? JSON.parse(localStorage.getItem('rangos')) : {},
    dataRangos: {},
    dataChart: {},
    changeTheme: null,
    coloresLeyend: JSON.parse(localStorage.getItem('leyenda')) != null ? JSON.parse(localStorage.getItem('leyenda')) : {},
    coloresLeyend: {},
    changeLegend: null,
    changeChart: null,
    changeMap: null,
    queryText: {},
    alias: null,
    valorTotal: null,
    pintarCluster: null,
    capas: {},
    legenTheme: null,
    legendChange: null,
    tipoVar: null,
    thematicTheme: null,
    tansparency: 8,
    listaVariables: [],
    labelsData: [],
    dataPie: [],
    changeLoader: null,
    changeData: null,
    updateData: null,
    filterGeo: null,
    deptoSelected: null,
    deptoSelectedFilter: null,
    deptoVariable: null,
    currentZoom: null,
    changeBarChartData: null,
    changePieChartData: null,
    changeDonuChartData: null,
    changeGaugeChartData: null,
    visualGroup: null,
    visualThematic: null,
    state: {
        labels: [],

        datasets: [
            {
                label: '',
                // labels: myLabels,
                backgroundColor: [],
                data: []
            }
        ]
    },
    structureUE: {
        "M": "Manzana",
        "E": "Edificación",
        "UE": "Unidad económica",
        "U": "Unidad",
        "EO": "Cantidad de unidades ocupadas",
        "ED": "Cantidad de unidades desocupadas",
        "EB": "Cantidad de unidades en obra",
        "EF": "Cantidad de unidades fijas",
        "ES": "Cantidad de unidades semifijas",
        "PM": "Cantidad de puestos móviles",
        "VA": "Cantidad de viviendas con actividad económica",
        "OBE": "Cantidad de obras en edificación",
        "SC": "Cantidad de unidades - comercio",
        "SI": "Cantidad de unidades - industria",
        "SS": "Cantidad de unidades - servicios",
        "ST": "Cantidad de unidades - transporte",
        "SCN": "Cantidad de unidades - construcción",
        "SN": "Cantidad de unidades - Sector no aplica",
        "LT": "Latitud",
        "LG": "Longitud",
    },
    unidadesCluster: null,
    distanceCluster: 0,
    loadUE: null,
    changeBaseMap: null,
    activeChart: null,
    baseMapPrev: "Gris",
    changeDepto: null,
    variableAnterior: null,
    municipioSeleccionado: null,
    apiGoogle: 'AIzaSyAOha4Su8EqOFQfDE8NjrS_KdSHfu50WkA',
    changeStyleDepto: null,
    changeStyleMpio: null,
    loadMzCentroids: null,
    unidadesMz: null,
    periodoSeleccionado: { value: '2021-12', label: '2021-12' },
    updatePeriodo: null,
    updatePeriodoHeader: null,
    loadDeptoCentroids: null,
    loadMpioCentroids: null,
    unidadesDepto: null,
    unidadesMpio: null,
    changeVisualization: null,
    updateCharTheme: null,
    updateLegendProportional: null,
    max: null,
    hideProportionalSymbols: null,
    updatePeriodoResult: null,
    periodos: null,
    listaProductos: null,
    productoSeleccionado: null,
    updateListaProductos: null,
    updateProductoSeleccionado: null,
    variablesCampos: {
        '%': 'VARIACION_PP',
        '$': 'PRECIO_PROMEDIO_ACTUAL'
    },
    updateSymbols: null,
    updateToProp: null,
    hideVisualizationSwitch: null,
    coloresDivergentes: {
        "0": "#ca0020",
        "1": "#f4a582",
        "2": "#f7f7f7",
        "3": "#92c5de",
        "4": "#0571b0"
    },
    updatePeriodoTabla: null,
    closer: null,
    updateToProps: null,
    updateProductoResult: null,
    updateProductotabla: null,
    transparencyGeneral: 10,
    versionMGN: "MGN 2022",
    updateActives: null,
    updateLayers: null,
    updateMGNHeader: null,
    ///herramientas de google//////
    marker: null,
    router: {
        line: null,
        start: null,
        finsih: null
    },
}
export const urlDeploy = 'http://localhost:3000/'